#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kartik Prabhu
# Date   : February 15, 2020
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:

  - sky130_sram_2kbyte_1rw1r_32x512_8.sp
  - sky130_sram_2kbyte_1rw1r_32x512_8.v
  - sky130_sram_2kbyte_1rw1r_32x512_8.lef
  - sky130_sram_2kbyte_1rw1r_32x512_8_tt_1p8V_25C.lib
  - sky130_sram_2kbyte_1rw1r_32x512_8.gds
  - sky130_sram_2kbyte_1rw1r_32x512_8_tt_1p8V_25C.db

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.sp              outputs/sky130_sram_2kbyte_1rw1r_32x512_8.sp
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.v               outputs/sky130_sram_2kbyte_1rw1r_32x512_8.v
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.lef             outputs/sky130_sram_2kbyte_1rw1r_32x512_8.lef
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.lib outputs/sky130_sram_2kbyte_1rw1r_32x512_8_tt_1p8V_25C.lib
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8.gds             outputs/sky130_sram_2kbyte_1rw1r_32x512_8.gds
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_2kbyte_1rw1r_32x512_8/sky130_sram_2kbyte_1rw1r_32x512_8_TT_1p8V_25C.db  outputs/sky130_sram_2kbyte_1rw1r_32x512_8_tt_1p8V_25C.db
